services:
  proxy-tatertalk:
    profiles:
      - proxy
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # SSL certificate files
      - ./.config/docker/certs:/etc/traefik/certs:ro
      # Dynamic configuration
      - ./.config/docker/dynamic:/etc/traefik/dynamic:ro
  tatertalk:
    profiles:
      - tatertalk
    build: .
    labels:
      - "traefik.http.services.tatertalk.loadbalancer.server.port=1420"
      - "traefik.http.routers.tatertalk-http.rule=Host(`tatertalk.docker.localhost`)"
      - "traefik.http.routers.tatertalk-http.entrypoints=web"
      - "traefik.http.routers.tatertalk-http.service=tatertalk"
      - "traefik.http.routers.tatertalk-https.rule=Host(`tatertalk.docker.localhost`)"
      - "traefik.http.routers.tatertalk-https.entrypoints=websecure"
      - "traefik.http.routers.tatertalk-https.tls=true"
      - "traefik.http.routers.tatertalk-https.service=tatertalk"
    develop:
      watch:
        # Sync source files
        - path: ./src
          action: sync
          target: /app/src
        # Sync public assets
        - path: ./public
          action: sync
          target: /app/public
        # Sync and restart for config files
        - path: .
          action: sync+restart
          target: /app
          include:
            - "*.config.js"
            - "*.config.ts"
            - "tsconfig.*"
            - ".env"
            - "index.html"
        # Rebuild for package management
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
