services:
  tatertalk:
    profiles:
      - tatertalk
    build: .
    labels:
      - "traefik.http.services.tatertalk.loadbalancer.server.port=1420"
      - "traefik.http.routers.tatertalk-http.rule=Host(`tatertalk.docker.localhost`)"
      - "traefik.http.routers.tatertalk-http.entrypoints=web"
      - "traefik.http.routers.tatertalk-http.service=tatertalk"
      - "traefik.http.routers.tatertalk-https.rule=Host(`tatertalk.docker.localhost`)"
      - "traefik.http.routers.tatertalk-https.entrypoints=websecure"
      - "traefik.http.routers.tatertalk-https.tls=true"
      - "traefik.http.routers.tatertalk-https.service=tatertalk"
    develop:
      watch:
        # Sync source files
        - path: ./src
          action: sync
          target: /app/src
        # Sync public assets
        - path: ./public
          action: sync
          target: /app/public
        # Sync and restart for config files
        - path: .
          action: sync+restart
          target: /app
          include:
            - "*.config.js"
            - "*.config.ts"
            - "tsconfig.*"
            - ".env"
            - "index.html"
        # Rebuild for package management
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
